from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_female = (
        "{{last_name}} {{middle_name}} {{first_name_female}}",
        "{{last_name}} {{middle_name}} {{first_name_unisex}}",
        "{{prefix_female}} {{last_name}} {{middle_name}} {{first_name_unisex}}",
        "{{prefix_female}} {{last_name}} {{middle_name}} {{first_name_female}}",
    )
    formats_male = (
        "{{last_name}} {{middle_name}} {{first_name_male}}",
        "{{last_name}} {{middle_name}} {{first_name_unisex}}",
        "{{prefix_male}} {{last_name}} {{middle_name}} {{first_name_unisex}}",
        "{{prefix_male}} {{last_name}} {{middle_name}} {{first_name_male}}",
    )
    formats = formats_female + formats_male

    # Name from : https://en.wikipedia.org/wiki/Vietnamese_name
    # and https://vinpearl.com/en/vietnamese-names-top-200-popular-names-for-boys-and-girls

    first_names_female = (
        'An',
        'Anh',
        'Ánh',
        'Bích',
        'Châu',
        'Chi',
        'Cúc',
        'Diễm',
        'Diệp',
        'Dung',
        'Dương',
        'Duyên',
        'Đào',
        'Giang',
        'Hà',
        'Hân',
        'Hạnh',
        'Hiền',
        'Hoa',
        'Hoài',
        'Hồng',
        'Huệ',
        'Huyền',
        'Hương',
        'Khánh',
        'Kiều',
        'Kim',
        'Lan',
        'Lê',
        'Liên',
        'Liễu',
        'Linh',
        'Loan',
        'Ly',
        'Mai',
        'Minh',
        'Mỹ',
        'Nga',
        'Ngân',
        'Ngọc',
        'Nguyệt',
        'Nhi',
        'Nhung',
        'Như',
        'Nương',
        'Phương',
        'Phượng',
        'Quyên',
        'Quỳnh',
        'Sao',
        'Sương',
        'Tâm',
        'Thanh',
        'Thảo',
        'Thi',
        'Thiên',
        'Thu',
        'Thương',
        'Thúy',
        'Thùy',
        'Thủy',
        'Tiên',
        'Trang',
        'Trâm',
        'Trinh',
        'Trúc',
        'Tú',
        'Tuyền',
        'Tuyết',
        'Tường',
        'Uyên',
        'Vân',
        'Vi',
        'Vy',
        'Xuân',
        'Xuyến',
        'Yên',
        'Yến',
    )

    first_names_unisex = (
        'An',
        'Anh',
        'Bảo',
        'Bình',
        'Châu',
        'Dương',
        'Giang',
        'Hải',
        'Hà',
        'Hiếu',
        'Hòa',
        'Hoàng',
        'Khánh',
        'Kim',
        'Lâm',
        'Linh',
        'Lương',
        'Minh',
        'Nghi',
        'Nguyên',
        'Nhân',
        'Nhật',
        'Ninh',
        'Phong',
        'Phú',
        'Phúc',
        'Phụng',
        'Phương',
        'Quân',
        'Quang',
        'Quyên',
        'Quỳnh',
        'Tâm',
        'Thanh',
        'Thảo',
        'Thiên',
        'Thịnh',
        'Thu',
        'Thủy',
        'Tiên',
        'Toàn',
        'Trúc',
        'Tú',
        'Tùng',
        'Tường',
        'Tuyên',
        'Uyên',
        'Việt',
        'Vinh',
        'Vũ',
        'Xuân',
        'Yên',
    )

    first_names_male = (
        'An',
        'Anh',
        'Bảo',
        'Bách',
        'Bình',
        'Cường',
        'Chí',
        'Chiến',
        'Công',
        'Dũng',
        'Dương',
        'Duy',
        'Đạt',
        'Đăng',
        'Đức',
        'Gia',
        'Giang',
        'Hải',
        'Hiếu',
        'Hiệp',
        'Hoàng',
        'Huy',
        'Hùng',
        'Hưng',
        'Khải',
        'Khanh',
        'Khánh',
        'Khoa',
        'Khôi',
        'Kiên',
        'Kiệt',
        'Khương',
        'Lâm',
        'Lân',
        'Long',
        'Lộc',
        'Lương',
        'Minh',
        'Mạnh',
        'Nam',
        'Nghĩa',
        'Nguyên',
        'Nhật',
        'Nhân',
        'Phong',
        'Phú',
        'Phúc',
        'Phước',
        'Phương',
        'Quân',
        'Quang',
        'Quốc',
        'Quyết',
        'Quý',
        'Sơn',
        'Sang',
        'Siêu',
        'Tài',
        'Tâm',
        'Tân',
        'Tấn',
        'Thái',
        'Thành',
        'Thắng',
        'Thanh',
        'Thiên',
        'Thịnh',
        'Thông',
        'Thuận',
        'Tiến',
        'Toàn',
        'Trí',
        'Trọng',
        'Trung',
        'Trường',
        'Tú',
        'Tuấn',
        'Tùng',
        'Tường',
        'Uy',
        'Vinh',
        'Việt',
        'Vương',
        'Vỹ',
        'Vũ',
        'Xuân',
    )

    middle_names = (
        'Văn',
        'Thị',
        'Minh',
        'Ngọc',
        'Thanh',
        'Gia',
        'Xuân',
        'Đức',
        'Kim',
        'Tuấn',
        'Quang',
        'Hữu',
        'Hoàng',
        'Thùy',
        'Phương',
        'Đình',
        'Hồng',
        'Thu',
        'Khánh',
        'Thảo',
        'Duy',
        'Nhã',
        'Cát',
        'Tường',
        'Bảo',
        'An',
        'Thái',
        'Thiên',
        'Trọng',
        'Việt',
        'Tú',
        'Mỹ',
        'Như',
        'Kim Ngọc',
        'Minh Anh',
        'Phương Thảo',
        'Thanh Trúc',
        'Tuệ Lâm',
        'Bảo Châu',
        'Ngọc Hân',
        'Gia Hân',
        'Hoàng Yến',
    )

    last_names = (
        'Nguyễn',
        'Trần',
        'Lê',
        'Phạm',
        'Hoàng', 
        'Huỳnh',
        'Phan',
        'Vũ', 
        'Võ',
        'Đặng',
        'Bùi',
        'Đỗ',
        'Hồ',
        'Ngô',
        'Dương',
        'Lý',
        'Vương',
        'Trịnh',
        'Trương',
        'Đinh',
        'Lâm',
        'Đoàn',
        'Mai',
        'Trịnh',
        'Đào',
        'Cao',
        'Hà',
        'Chung',
        'Thân',
        'Quách',
        'Lương',
        'Bạch',
        'Phùng',
        'Tô',
        'Tạ',
        'Tống',
        'Khúc',
        'Thạch',
        'Lưu',
        'Mạc',
        'Chu',
        'Từ',
        'Diệp',
        'Nông',
    )

    # Typically, Vietnamese will be addressed with their given name and a prefix
    # https://en.wikipedia.org/wiki/Vietnamese_name#Given_name

    prefixes_female = ("Cô", "Chị", "Bà", "Quý cô", "Bác")

    prefixes_male = ("Ông", "Anh", "Bác", "Quý ông", "Chú")

    def first_name_unisex(self) -> str:
        return self.random_element(self.first_names_unisex)

    def middle_name(self) -> str:
        return self.random_element(self.middle_names)
